apiVersion: v1
kind: Service
metadata:
  labels:
    app: simpleapp-go
  name: simpleapp-go
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 80
      protocol: TCP
  selector:
    app: simpleapp-go  
